-- Finding total product by category 
SELECT category, COUNT(DISTINCT product_key) as total_product
FROM dim_products
GROUP BY category 
ORDER BY total_product desc;

-- Finding the average costs of each category 
SELECT category, AVG(cost) as average_cost
FROM dim_products
GROUP BY category
ORDER BY average_cost desc;

-- Finding each category that generated total revenue 
SELECT p.category , SUM(f.sales_amount) as total_revenue
FROM fact_sales as f
LEFT JOIN dim_products as p
ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue desc;

-- Finding what is the total revenue generated by each customer 
SELECT first_name, last_name, country, SUM(f.sales_amount) as total_revenue
FROM fact_sales as f
LEFT JOIN dim_customers as c
ON f.customer_key = c.customer_key
GROUP BY  first_name, last_name, country
ORDER BY total_revenue DESC;

-- Finding the distribution of sold item across countries
SELECT country, SUM(quantity) as total_sold_product
FROM dim_customers as c
LEFT JOIN fact_sales as f
ON f.customer_key = c.customer_key
GROUP BY country 
ORDER BY total_sold_product DESC;

-- -------------------------------------------------------------------------------------------
-- Finding top 5 product the highest revenue 
SELECT *
FROM (
	SELECT p.product_name ,  
		SUM(f.sales_amount) as total_revenue,
		ROW_NUMBER () OVER( ORDER BY SUM(f.sales_amount) DESC ) as rank_products
	FROM fact_sales as f
	LEFT JOIN dim_products as p
	ON f.product_key = p.product_key
	GROUP BY p.product_name) as subquery
WHERE rank_products <=5;

-- Finding the worst 5 performing  product 

SELECT p.product_name , category , subcategory, SUM(f.sales_amount) as total_revenue
FROM fact_sales as f
LEFT JOIN dim_products as p
ON f.product_key = p.product_key
GROUP BY p.product_name, category, subcategory
ORDER BY total_revenue ASC
LIMIT 5 ;

-- Finding top 5 subcategory the highest revenue 
SELECT p.subcategory , p.category ,SUM(f.sales_amount) as total_revenue
FROM fact_sales as f
LEFT JOIN dim_products as p
ON f.product_key = p.product_key
GROUP BY p.subcategory, p.category
ORDER BY total_revenue DESC
LIMIT 5 ;

-- Finding the worst 3 subcategory 
SELECT p.subcategory , p.category ,SUM(f.sales_amount) as total_revenue
FROM fact_sales as f
LEFT JOIN dim_products as p
ON f.product_key = p.product_key
GROUP BY p.subcategory, p.category
ORDER BY total_revenue ASC
LIMIT 3 ;